name: 'unit test'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  workflow_call:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}-ci'
  cancel-in-progress: true

jobs:

  # go_lint:
  #   uses: 'abcxyz/pkg/.github/workflows/go-lint.yml@main'
  #   with:
  #     go_version: '1.19'

  go_test:
    uses: 'abcxyz/pkg/.github/workflows/go-test.yml@cc2b918b16df0f627b933ed8dddf0d846fa9108b' # ratchet:abcxyz/pkg/.github/workflows/go-test.yml@main
    with:
      go_version: '1.19'
